name: shopperz
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.1+7

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.7.3
  get_storage: ^2.1.1
  google_fonts: ^8.0.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  carousel_slider: ^5.1.2
  dots_indicator: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  dotted_line: ^3.2.3
  image_picker: ^1.2.1
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  dio: ^5.9.1
  shimmer: ^3.0.0
  http: ^1.6.0
  google_maps_flutter: ^2.14.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  country_state_city_picker: ^1.2.8
  dropdown_search: ^6.0.2
  country_code_picker: ^3.4.1
  fluttertoast: ^9.0.0
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.1
  printing: ^5.14.2
  flutter_html: ^3.0.0
  youtube_player_flutter: ^9.1.3
  firebase_messaging: ^16.1.1
  firebase_core: ^4.4.0
  flutter_local_notifications: ^20.1.0
  flutter_inappwebview: ^6.1.5
  logger: ^2.6.2
  connectivity_plus: ^7.0.0
  shared_preferences: ^2.5.4
  flutter_spinkit: ^5.2.2
  sqflite: ^2.4.2
  flutter_widget_from_html_core: ^0.17.0
#test
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/product-details/

